/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import AI.CourseClass;
import AI.Professor;
import AI.Schedule;
import AI.StudentsGroup;
import Model.InputFromMySQL;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KING
 */
public class ViewSoftContraints extends javax.swing.JFrame {
    private static final int DAY_HOURS = ViewSchedule.getDAY_HOURS();
    private static final int ROOM_NUM = ViewSchedule.getROOM_NUM();

    /**
     * Creates new form ViewSoftContraints
     */
    public ViewSoftContraints() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCheck = new javax.swing.JMenu();
        miProf = new javax.swing.JMenuItem();
        miGroup = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check Soft Contraints");
        setLocation(new java.awt.Point(500, 150));

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tab1.setEnabled(false);
        jScrollPane1.setViewportView(tab1);

        mCheck.setText("Check");

        miProf.setText("Professors");
        miProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfActionPerformed(evt);
            }
        });
        mCheck.add(miProf);

        miGroup.setText("Students Groups");
        miGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGroupActionPerformed(evt);
            }
        });
        mCheck.add(miGroup);

        jMenuBar1.add(mCheck);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfActionPerformed
        Schedule schedule = ViewSchedule.getGA().getBestOfBest();
        tab1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                },
                new String[]{
                    "ID_Professor", "Name", "Day", "Class","Class",
                })
        );
        DefaultTableModel model = (DefaultTableModel) tab1.getModel();
        int daySize = DAY_HOURS * ROOM_NUM;
        String[] getDay;
        getDay = new String[] {"Monday","Tuesday","Wednesday","Thursday","Friday"};
        ArrayList<CourseClass> classList = InputFromMySQL.getClassList();
        //Xet tung giao vien xem co vi pham rang buoc mem khong?
        for(Professor pr : InputFromMySQL.getProfList()) {
            ArrayList<CourseClass> class_list = pr.getCourseClasses();
            for(int i=0; i < class_list.size()-1; i++) {
                
                int index1 = classList.indexOf(class_list.get(i));
                int day1 = schedule.getClasses().get(index1) / daySize;
                int room1 = ( schedule.getClasses().get(index1) % daySize ) / DAY_HOURS;
                
                for( int j=i+1; j < class_list.size(); j++) {
                    
                    int index2 = classList.indexOf(class_list.get(j));
                    int day2 = schedule.getClasses().get(index2) / daySize;
                    int room2 = ( schedule.getClasses().get(index2) % daySize ) / DAY_HOURS;
                    
                    if((day2 == day1) && ( InputFromMySQL.getRoomById(room1).getDistance() != InputFromMySQL.getRoomById(room2).getDistance())) {
                        model.addRow(new Object[] { 
                            pr.getId(), pr.getName(), getDay[day1], class_list.get(i).getId(), class_list.get(j).getId() 
                        });
                    }
                }
            }
        } 
    }//GEN-LAST:event_miProfActionPerformed

    private void miGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGroupActionPerformed
        Schedule schedule = ViewSchedule.getGA().getBestOfBest();
        tab1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                },
                new String[]{
                    "ID_Group", "Name", "Day", "Class","Class",
                })
        );
        DefaultTableModel model = (DefaultTableModel) tab1.getModel();
        int daySize = DAY_HOURS * ROOM_NUM;
        String[] getDay;
        getDay = new String[] {"Monday","Tuesday","Wednesday","Thursday","Friday"};
        ArrayList<CourseClass> classList = InputFromMySQL.getClassList();
        //Xet tung group xem co vi pham rang buoc mem khong?
        for(StudentsGroup gr : InputFromMySQL.getGroupList()) {
            ArrayList<CourseClass> class_list = gr.getCourseClasses();
            for(int i=0; i < class_list.size()-1; i++) {
                
                int index1 = classList.indexOf(class_list.get(i));
                int day1 = schedule.getClasses().get(index1) / daySize;
                int room1 = ( schedule.getClasses().get(index1) % daySize ) / DAY_HOURS;
                
                for( int j=i+1; j < class_list.size(); j++) {
                    
                    int index2 = classList.indexOf(class_list.get(j));
                    int day2 = schedule.getClasses().get(index2) / daySize;
                    int room2 = ( schedule.getClasses().get(index2) % daySize ) / DAY_HOURS;
                    
                    if((day2 == day1) && ( InputFromMySQL.getRoomById(room1).getDistance() != InputFromMySQL.getRoomById(room2).getDistance())) {
                        model.addRow(new Object[] { gr.getId(),gr.getName(),getDay[day1],class_list.get(i).getId(),class_list.get(j).getId() });
                    }
                }
            }
        } 
    }//GEN-LAST:event_miGroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSoftContraints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSoftContraints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSoftContraints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSoftContraints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSoftContraints().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mCheck;
    private javax.swing.JMenuItem miGroup;
    private javax.swing.JMenuItem miProf;
    private javax.swing.JTable tab1;
    // End of variables declaration//GEN-END:variables
}
